name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v1

    # - name: Run a one-line script
    #   run: echo Hello, world!

    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.

    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install yarn -g
    - run: yarn
    - run: yarn test
    - run: yarn build
    - run: yarn package
